/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        setupContentPanel();
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LogoButton = new javax.swing.JButton();
        SKofficialsButton = new javax.swing.JToggleButton();
        AnnouncementButton = new javax.swing.JToggleButton();
        SKrecordButton = new javax.swing.JToggleButton();
        LogoutButton = new javax.swing.JButton();
        leftDashboard = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setBackground(new java.awt.Color(0, 51, 153));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoButton.setBackground(new java.awt.Color(0, 0, 0));
        LogoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Logo.png"))); // NOI18N
        LogoButton.setContentAreaFilled(false);
        LogoButton.addActionListener(this::LogoButtonActionPerformed);
        jPanel1.add(LogoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 230, 90));

        SKofficialsButton.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        SKofficialsButton.setForeground(new java.awt.Color(0, 0, 153));
        SKofficialsButton.setText("SK OFFICIALS RECORDS");
        SKofficialsButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 102)));
        SKofficialsButton.setContentAreaFilled(false);
        SKofficialsButton.addActionListener(this::SKofficialsButtonActionPerformed);
        jPanel1.add(SKofficialsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 230, 40));

        AnnouncementButton.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        AnnouncementButton.setForeground(new java.awt.Color(0, 0, 153));
        AnnouncementButton.setText("ANNOUNCEMENT");
        AnnouncementButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 102)));
        AnnouncementButton.setContentAreaFilled(false);
        AnnouncementButton.addActionListener(this::AnnouncementButtonActionPerformed);
        jPanel1.add(AnnouncementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 230, 40));

        SKrecordButton.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        SKrecordButton.setForeground(new java.awt.Color(0, 0, 153));
        SKrecordButton.setText("SK RESIDENCE RECORDS");
        SKrecordButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 102)));
        SKrecordButton.setContentAreaFilled(false);
        SKrecordButton.addActionListener(this::SKrecordButtonActionPerformed);
        jPanel1.add(SKrecordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 230, 40));

        LogoutButton.setBackground(new java.awt.Color(153, 0, 0));
        LogoutButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setText("LOG OUT");
        LogoutButton.addActionListener(this::LogoutButtonActionPerformed);
        jPanel1.add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 230, 40));

        leftDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/LeftDashBoard.gif"))); // NOI18N
        jPanel1.add(leftDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 700));

        MainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 700));

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));
        jPanel3.setLayout(new java.awt.CardLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/DashboardBGSCR.jpg"))); // NOI18N
        jPanel3.add(jLabel2, "card2");

        jScrollPane1.setViewportView(jPanel3);

        MainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 890, 700));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoButtonActionPerformed

    private void SKofficialsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SKofficialsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SKofficialsButtonActionPerformed

    private void AnnouncementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnouncementButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnnouncementButtonActionPerformed

    private void SKrecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SKrecordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SKrecordButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AnnouncementButton;
    private javax.swing.JButton LogoButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JToggleButton SKofficialsButton;
    private javax.swing.JToggleButton SKrecordButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel leftDashboard;
    // End of variables declaration//GEN-END:variables

    private void setupContentPanel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
