/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class LogInPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LogInPage.class.getName());

    /**
     * Creates new form LogInPage
     */
    public LogInPage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        LGNpageLPanel = new javax.swing.JPanel();
        Poster = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LGNpageRPanel = new javax.swing.JPanel();
        UnameField = new javax.swing.JTextField();
        PwordField = new javax.swing.JPasswordField();
        LoginBtn = new javax.swing.JButton();
        showPword = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Barangay SK Tracker System");
        setBounds(new java.awt.Rectangle(0, 0, 1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setPreferredSize(new java.awt.Dimension(1200, 700));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LGNpageLPanel.setPreferredSize(new java.awt.Dimension(770, 700));
        LGNpageLPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Poster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/LogINPageBG.jpg"))); // NOI18N
        LGNpageLPanel.add(Poster, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, -1));

        jLabel1.setText("jLabel1");
        LGNpageLPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        MainPanel.add(LGNpageLPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 700));

        LGNpageRPanel.setBackground(new java.awt.Color(0, 0, 153));
        LGNpageRPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UnameField.setBackground(new java.awt.Color(0,0,0,0));
        UnameField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        UnameField.setForeground(new java.awt.Color(255, 255, 255));
        UnameField.setToolTipText("");
        UnameField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)), "Username", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_BOTTOM, new java.awt.Font("Arial", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        UnameField.setCaretColor(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        UnameField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        UnameField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        UnameField.addActionListener(this::UnameFieldActionPerformed);
        LGNpageRPanel.add(UnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 230, 50));

        PwordField.setBackground(new java.awt.Color(0,0,0,0));
        PwordField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PwordField.setForeground(new java.awt.Color(255, 255, 255));
        PwordField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)), "Password", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_BOTTOM, new java.awt.Font("Arial", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        PwordField.setCaretColor(new java.awt.Color(255, 255, 255));
        PwordField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        PwordField.addActionListener(this::PwordFieldActionPerformed);
        LGNpageRPanel.add(PwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 230, 50));

        LoginBtn.setBackground(new java.awt.Color(0, 51, 153));
        LoginBtn.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("LOG IN");
        LoginBtn.addActionListener(this::LoginBtnActionPerformed);
        LGNpageRPanel.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 230, 40));
        LoginBtn.getAccessibleContext().setAccessibleDescription("LoginBtn");

        showPword.setForeground(new java.awt.Color(255, 255, 255));
        showPword.setText("show password");
        showPword.addActionListener(this::showPwordActionPerformed);
        LGNpageRPanel.add(showPword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 110, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\OneDrive\\Desktop\\Sk_System_Asset\\LogINVerify2.jpg")); // NOI18N
        LGNpageRPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MainPanel.add(LGNpageRPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 400, 700));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnameFieldActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
  String username = UnameField.getText();
  String password = new String(PwordField.getPassword());

    if (username.equals("admin") && password.equals("admin123")) {

        // SUCCESS POP-UP
        javax.swing.JOptionPane.showMessageDialog(this,
                "Login Successfully!",
                "Success",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // OPEN DASHBOARD
        Dashboard dash = new Dashboard();
        dash.setVisible(true);

        // CLOSE LOGIN PAGE
        this.dispose();

    } else {

        // FAILED POP-UP
        javax.swing.JOptionPane.showMessageDialog(this,
                "Login Failed! Incorrect username or password.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void showPwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPwordActionPerformed
        // TODO add your handling code here:
            if (showPword.isSelected()) {
        PwordField.setEchoChar((char) 0);   // SHOW password
    } else {
        PwordField.setEchoChar('*');        // HIDE password
    }
    }//GEN-LAST:event_showPwordActionPerformed

    private void PwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PwordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LogInPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LGNpageLPanel;
    private javax.swing.JPanel LGNpageRPanel;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel Poster;
    private javax.swing.JPasswordField PwordField;
    private javax.swing.JTextField UnameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox showPword;
    // End of variables declaration//GEN-END:variables
}
